# Generated by Django 2.0.7 on 2018-07-18 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='accounts')),
                ('address', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('birth_day', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Men', 'Nam'), ('Women', 'Nữ')], max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
