# Generated by Django 2.0.7 on 2018-07-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180719_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='accounts/default.png', null=True, upload_to='accounts'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('Men', 'Nam'), ('Women', 'Nữ')], max_length=100),
        ),
    ]
