# Generated by Django 2.0.7 on 2018-07-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180721_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('Men', 'Nam'), ('Women', 'Nữ')], max_length=100),
        ),
    ]
