# Generated by Django 2.0.7 on 2018-07-23 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180721_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('Women', 'Nữ'), ('Men', 'Nam')], max_length=100),
        ),
    ]
