# Generated by Django 2.0.7 on 2018-07-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180723_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('Men', 'Nam'), ('Women', 'Nữ')], max_length=100),
        ),
    ]
