# Generated by Django 2.0.7 on 2018-07-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('status', models.NullBooleanField(default=True)),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
                ('Modified_At', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
