# Generated by Django 2.0.7 on 2018-07-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='about')),
                ('column', models.CharField(choices=[('column 1', 'Cột 1'), ('column 2', 'Cột 2')], default='column 1', max_length=200)),
            ],
        ),
    ]
