# Generated by Django 2.0.7 on 2018-07-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='des',
            field=models.TextField(null=True),
        ),
    ]
