# Generated by Django 2.0.7 on 2018-07-18 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_about_des'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='column',
            field=models.CharField(choices=[('column 2', 'Cột 2'), ('column 1', 'Cột 1')], default='column 1', max_length=200),
        ),
    ]
