# Generated by Django 2.0.7 on 2018-07-21 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20180718_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='column',
            field=models.CharField(choices=[('column 1', 'Cột 1'), ('column 2', 'Cột 2')], default='column 1', max_length=200),
        ),
    ]
