# Generated by Django 2.0.7 on 2018-07-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_auto_20180721_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='column',
            field=models.CharField(choices=[('column 2', 'Cột 2'), ('column 1', 'Cột 1')], default='column 1', max_length=200),
        ),
    ]
