# Generated by Django 2.0.7 on 2018-07-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_auto_20180724_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='column',
            field=models.CharField(choices=[('column 1', 'Cột 1'), ('column 2', 'Cột 2')], default='column 1', max_length=200),
        ),
    ]
