# Generated by Django 2.0.7 on 2018-07-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='1', max_length=150),
        ),
    ]
