# Generated by Django 2.0.7 on 2018-08-03 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20180803_2349'),
        ('orders', '0002_auto_20180725_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupon', to='products.Coupouns'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.IntegerField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='shiped_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
