# Generated by Django 2.0.7 on 2018-07-17 15:02

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20180717_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_detail',
            name='color',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Green', 'Xanh nước biển'), ('Black', 'Đen'), ('Grey', 'Xám'), ('Blue', 'Xanh da trời'), ('Red', 'Đỏ'), ('White', 'Trắng'), ('Orange', 'Da cam')], default='Black', max_length=10),
        ),
        migrations.AlterField(
            model_name='product_detail',
            name='size',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XXL', 'XXL'), ('XL', 'XL')], default='L', max_length=10),
        ),
    ]
