# Generated by Django 2.0.7 on 2018-07-17 15:05

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20180717_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_detail',
            name='color',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Grey', 'Xám'), ('Orange', 'Da cam'), ('Black', 'Đen'), ('White', 'Trắng'), ('Red', 'Đỏ'), ('Blue', 'Xanh da trời'), ('Green', 'Xanh nước biển')], default='Black', max_length=50),
        ),
        migrations.AlterField(
            model_name='product_detail',
            name='size',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('S', 'S'), ('XXL', 'XXL')], default='L', max_length=50),
        ),
    ]
