# Generated by Django 2.0.7 on 2018-07-17 16:32

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20180717_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_detail',
            name='color',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Blue', 'Xanh da trời'), ('Green', 'Xanh nước biển'), ('Black', 'Đen'), ('Red', 'Đỏ'), ('Grey', 'Xám'), ('White', 'Trắng'), ('Orange', 'Da cam')], default='Black', max_length=50),
        ),
        migrations.AlterField(
            model_name='product_detail',
            name='size',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('XL', 'XL'), ('M', 'M'), ('S', 'S'), ('XXL', 'XXL'), ('L', 'L')], default='L', max_length=50),
        ),
    ]
