# Generated by Django 2.0.7 on 2018-07-17 16:42

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20180717_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_detail',
            name='color',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Blue', 'Xanh da trời'), ('Black', 'Đen'), ('Grey', 'Xám'), ('Orange', 'Da cam'), ('Red', 'Đỏ'), ('Green', 'Xanh nước biển'), ('White', 'Trắng')], default='Black', max_length=50),
        ),
        migrations.AlterField(
            model_name='product_detail',
            name='size',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('XXL', 'XXL'), ('S', 'S'), ('XL', 'XL'), ('M', 'M'), ('L', 'L')], default='L', max_length=50),
        ),
    ]
