# Generated by Django 2.0.7 on 2018-07-21 02:54

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20180718_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_detail',
            name='color',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('White', 'Trắng'), ('Green', 'Xanh nước biển'), ('Blue', 'Xanh da trời'), ('Orange', 'Da cam'), ('Red', 'Đỏ'), ('Grey', 'Xám'), ('Black', 'Đen')], default='Black', max_length=50),
        ),
        migrations.AlterField(
            model_name='product_detail',
            name='materials',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product_detail',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_detail', to='products.Product'),
        ),
        migrations.AlterField(
            model_name='product_detail',
            name='size',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('XL', 'XL'), ('M', 'M'), ('L', 'L'), ('XXL', 'XXL'), ('S', 'S')], default='L', max_length=50),
        ),
        migrations.AlterField(
            model_name='product_image',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='products.Product'),
        ),
    ]
