# Generated by Django 2.0.7 on 2018-07-24 15:11

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20180723_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_new',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='product_detail',
            name='color',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Blue', 'Blue'), ('Red', 'Red'), ('White', 'White'), ('Black', 'Black'), ('Orange', 'Orange'), ('Grey', 'Grey'), ('Green', 'Green')], default='Black', max_length=50),
        ),
        migrations.AlterField(
            model_name='product_detail',
            name='size',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('XL', 'XL'), ('XXL', 'XXL'), ('M', 'M'), ('S', 'S'), ('L', 'L')], default='L', max_length=50),
        ),
    ]
