# Generated by Django 2.0.7 on 2018-07-27 03:58

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20180725_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_detail',
            name='color',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Blue', 'Blue'), ('Orange', 'Orange'), ('Red', 'Red'), ('Grey', 'Grey'), ('Black', 'Black'), ('Green', 'Green'), ('White', 'White')], default='Black', max_length=50),
        ),
        migrations.AlterField(
            model_name='product_detail',
            name='size',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('M', 'M'), ('S', 'S'), ('XXL', 'XXL'), ('L', 'L'), ('XL', 'XL')], default='L', max_length=50),
        ),
    ]
