# Generated by Django 2.0.7 on 2018-07-30 04:20

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20180727_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_new',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='product_detail',
            name='color',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('White', 'White'), ('Red', 'Red'), ('Green', 'Green'), ('Black', 'Black'), ('Blue', 'Blue'), ('Orange', 'Orange'), ('Grey', 'Grey')], default='Black', max_length=50),
        ),
        migrations.AlterField(
            model_name='product_detail',
            name='size',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('M', 'M'), ('XXL', 'XXL'), ('S', 'S'), ('XL', 'XL'), ('L', 'L')], default='L', max_length=50),
        ),
    ]
