# Generated by Django 2.0.7 on 2018-08-03 14:24

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20180803_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupouns',
            name='valid_from',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='coupouns',
            name='valid_to',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='coupouns',
            name='code',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='product_detail',
            name='color',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Green', 'Green'), ('Red', 'Red'), ('Orange', 'Orange'), ('Grey', 'Grey'), ('Blue', 'Blue'), ('White', 'White'), ('Black', 'Black')], default='Black', max_length=50),
        ),
        migrations.AlterField(
            model_name='product_detail',
            name='size',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('XL', 'XL'), ('M', 'M'), ('XXL', 'XXL'), ('L', 'L'), ('S', 'S')], default='L', max_length=50),
        ),
    ]
