# Generated by Django 2.0.7 on 2018-08-03 16:49

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20180803_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_detail',
            name='color',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Red', 'Red'), ('Black', 'Black'), ('Green', 'Green'), ('Blue', 'Blue'), ('Grey', 'Grey'), ('White', 'White'), ('Orange', 'Orange')], default='Black', max_length=50),
        ),
        migrations.AlterField(
            model_name='product_detail',
            name='size',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('L', 'L'), ('S', 'S'), ('XL', 'XL'), ('M', 'M'), ('XXL', 'XXL')], default='L', max_length=50),
        ),
    ]
