# Generated by Django 2.0.7 on 2018-08-04 02:13

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20180803_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupouns',
            name='product',
        ),
        migrations.AlterField(
            model_name='product_detail',
            name='color',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Blue', 'Blue'), ('Grey', 'Grey'), ('White', 'White'), ('Orange', 'Orange'), ('Green', 'Green'), ('Red', 'Red'), ('Black', 'Black')], default='Black', max_length=50),
        ),
        migrations.AlterField(
            model_name='product_detail',
            name='size',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('S', 'S'), ('XL', 'XL'), ('M', 'M'), ('XXL', 'XXL'), ('L', 'L')], default='L', max_length=50),
        ),
    ]
