# Generated by Django 2.0.7 on 2018-08-04 02:44

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_auto_20180804_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_detail',
            name='color',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Blue', 'Blue'), ('Black', 'Black'), ('Grey', 'Grey'), ('Orange', 'Orange'), ('Red', 'Red'), ('White', 'White'), ('Green', 'Green')], default='Black', max_length=50),
        ),
        migrations.AlterField(
            model_name='product_detail',
            name='size',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('M', 'M'), ('L', 'L'), ('S', 'S'), ('XXL', 'XXL'), ('XL', 'XL')], default='L', max_length=50),
        ),
    ]
