# Generated by Django 2.0.7 on 2018-08-04 06:38

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_auto_20180804_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_detail',
            name='color',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Black', 'Black'), ('White', 'White'), ('Red', 'Red'), ('Orange', 'Orange'), ('Green', 'Green'), ('Grey', 'Grey'), ('Blue', 'Blue')], default='Black', max_length=50),
        ),
        migrations.AlterField(
            model_name='product_detail',
            name='size',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('M', 'M'), ('S', 'S'), ('L', 'L'), ('XXL', 'XXL'), ('XL', 'XL')], default='L', max_length=50),
        ),
    ]
